### ISSUE TITLE
Labor Socioeconomic Scaling

### ISSUE THREAD

**Issue by emcduffie** [USEPA/FrEDI#126]
FrEDI labor impacts are not changing with changes in population inputs. When run with default temperature and GDP profiles, FrEDI outputs the same results for both annual_impacts and physical_impacts when run with two different population inputs. 

Sample code:
`load('sysdata.rda')

##### RUN POPULATION VARIATIONS ------------------------------------------------

#Define 2x and .5x population pathways (Otherwise use the default scenarios)
pop_path_double <-  rDataList[['pop_default']] %>% mutate(reg_pop=2*reg_pop)
pop_path_default <- rDataList[['pop_default']]
pop_path_half <-    rDataList[['pop_default']] %>% mutate(reg_pop=.5*reg_pop)

#Get results for our three paths of interest
double_pop <- run_fredi(inputsList=list(tempInput = NULL, 
                                                slrInput  = NULL, 
                                                gdpInput  = NULL, 
                                                popInput  = pop_path_double),
                        aggLevels =c('national','modelaverage'),
                        sectorList = 'Labor') %>% 
  filter(region=='National Total')

default_pop <- run_fredi(inputsList=list(tempInput = NULL, 
                                         slrInput  = NULL, 
                                         gdpInput  = NULL, 
                                         popInput  = pop_path_default),
                         aggLevels =c('national', 'modelaverage'),
                         sectorList = 'Labor') %>% 
  filter(region=='National Total')

half_pop <- run_fredi(inputsList=list(tempInput = NULL, 
                                      slrInput  = NULL, 
                                      gdpInput  = NULL, 
                                      popInput  = pop_path_half),
                      aggLevels =c('national','modelaverage'),
                      sectorList = 'Labor') %>% 
  filter(region=='National Total')

##### CHECK OUT WHAT CHANGES ---------------------------------------------------

#Do labor damages change in any period?
all(double_pop$annual_damages==default_pop$annual_damages) #Outputs "TRUE"
all(half_pop$annual_damages==default_pop$annual_damages) #Outputs "TRUE"`

**Comment by tonygard-indecon** [comment]
@emcduffie Which branch did you use?

**Comment by emcduffie** [comment]
@tonygard-indecon  - I was on the @main branch, I believe using the @FrEDI_2300 tagged release.

**Comment by knoiva-indecon** [comment]
@emcduffie : @heaston-indecon and I did some tests and tracking and we are thinking this behavior is a consequence of the nature of the scenarios you chose and our methods for calculating economic scalars. So, a special case, but not a bug. Hugh and I are writing up some notes and will explain further

**Comment by emcduffie** [comment]
Additional tests confirmed that FrEDI Labor sector calculations are working as expected. No coding changes required. 

Summary: Monetization is conducted by calculating wage rates scaled proportionally to the ratio of GDP per capita in each year relative to GDP per capita in 2010. Relative to the default scenario, if population and/or GDP are scaled by the same factor across the entire timeseries, the ratio of GDP per capita each year relative to that in 2010 does not change relative to that same ratio in the default scenario.
