### ISSUE TITLE
Rethink how adaptation variants are presented

### ISSUE THREAD

**Issue by cahartin** [USEPA/FrEDI#55]
In a lot of the sectors we label them as 'no adaptation'.  That means there are no adaptation options to pick from in the FrEDI code, however that does not mean that the underlying study does not have adaptation within.

**Comment by knoiva-indecon** [comment]
We typically use the label "No Adaptation" in cases where there are multiple adaptation options. If there are no other options, we typically use the label "N/A" for "Not Applicable"

**Comment by cahartin** [comment]
updated in the latest technical documentation
