### ISSUE TITLE
run_fredi() silentFlag

### ISSUE THREAD

**Issue by emcduffie** [USEPA/FrEDI#57]
run_fredi() module exits with an error when run with silentFlag = FALSE. 

Module runs normally when silentFlag = TRUE (default)

To do: either disable flag or remove as a user input option. 

@knoiva-indecon

**Comment by emcduffie** [comment]
@knoiva-indecon  - can we fix this in the next update?

**Comment by knoiva-indecon** [comment]
Yes, can do. Thanks for the heads up
