### ISSUE TITLE
run_fredi() default income elasticity

### ISSUE THREAD

**Issue by emcduffie** [USEPA/FrEDI#58]
Lines 90-100 in the run_fredi.R code specify the default values for each of the run_fredi() input parameters. 

It would be helpful to list the default income elasticity value here too. 

@knoiva-indecon

**Comment by knoiva-indecon** [comment]
Added additional info to documentation for elasticity flag for `run_fredi`, to clarify that the default elasticity value depends on the sector. Rebuilt documentation and package.
