### ISSUE TITLE
add contributor guidelines to repo

### ISSUE THREAD

**Issue by cahartin** [USEPA/FrEDI#69]
maybe add in some info on what makes a good study to incorporate into FrEDI

**Comment by cahartin** [comment]
when peer reviewed, standards for data incorporation, getting in contact with us....

**Comment by emcduffie** [comment]
develop a "How to Contribute" page that addresses these (added 'coming soon' page for now)

**Comment by emcduffie** [comment]
moved to a broader documentation issue focused on all outstanding io items
