### ISSUE TITLE
potentially delete these functionalities 

### ISSUE THREAD

**Issue by cahartin** [USEPA/FrEDI#72]
pvFlag <- NULL 
  Purpose: 
     Calculate the present value of annual monetized impacts
   Options: TRUE/FALSE.
   Default: FALSE

rateFlag <- NULL         
   Purpose: 
     If pvFlag = TRUE, specify the annual constant discount rate used 
     to calculate present values
   Default: 0.03

**Comment by knoiva-indecon** [comment]
We can delete these since we don't tend to use them. Let me know.

**Comment by knoiva-indecon** [comment]
We will delete these on the next set of FrEDI changes

**Comment by cahartin** [comment]
@knoiva-indecon can we close this issue?

**Comment by knoiva-indecon** [comment]
@cahartin : I believe they are still in the function. I'd like to keep this issue open until we make the update. This should be easy to change, but since it does affect the model code, I don't want to implement this until we can test it, so I plan to implement it with other changes.

**Comment by knoiva-indecon** [comment]
Deleted in December.
