### ISSUE TITLE
FrEDI sv module not running

### ISSUE THREAD

**Issue by emcduffie** [USEPA/FrEDI#74]
`run_fredi_sv()` quits with the following error: `Error in str_match(., col0) : could not find function "str_match"`

I had flagged this in a previous issue that seems to have been deleted. I used to run `run_fredi_sv()` from the 'sv_template_update' branch, but that branch was also recently deleted. 

Please prioritize this fix.

**Comment by knoiva-indecon** [comment]
On it! Just alerted to this last night. I'll try to fix it by tomorrow. In the short term, I think we just need to add the svDataList to the model data. In the slightly longer term, working to set up GitHub actions and piggyback to revamp the data configuration process to avoid this issue in the future.
